var shoesArray = [
    {id: 1, name: "Nike Air Max 97", gender: "Men's Shoe", colour: "White", price: "R 3 099.95", image: "./assets/img/Nike Air Max 97 White.jpg", detailImage: "./assets/img/nike 1.png" , rating: "", description: "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead. Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort."},
    {id: 2, name: "Nike Air Max 90", gender: "Men's Shoe", colour: "Black", price: "R 2 499.95", image: "./assets/img/Nike Air Max 90 Black.jpg", detailImage: "./assets/img/nike 2.png" , rating: "", description: "The Nike Air Max 90 Surplus adds soldier style to the athletics classic with large rubber lugs, tough overlays and durable TPU accents. Military-inspired colours combine with the composite toe cap (think hardcore work boots) and an internal stash pocket on the gusseted tongue. Winter or not, here you come."},
    {id: 3, name: "Nike Air Force 1 LV8", gender: "Men's Shoe", colour: "Blue", price: "R 1 799.95", image: "./assets/img/Nike Air Force 1 LV8 White.jpg", detailImage: "./assets/img/nike 3.png" , rating: "", description: "Elevate to legendary status in the Nike Air Force 1 '07 LV8. Refreshed colours highlight the premium details that landed this iconic design at the pinnacle of sneaker culture."},
    {id: 4, name: "Nike Air Max 2090", gender: "Women's Shoe", colour: "Pink", price: "R 2 499.95", image: "./assets/img/Nike Air Max 2090 Pink.jpg", detailImage: "./assets/img/nike 4.png" , rating: "", description: "The Nike Air Max 2090 turns up an icon—30 years after the OG Air Max 90—with even more Air. Lightweight and breathable for little walkers. A see-through design peeks into the future of Max Air"},
    {id: 5, name: "Nike Air Max 95", gender: "Women's Shoe", colour: "White", price: "R 2 899.95", image: "./assets/img/Nike Air Max 95 White.jpg", detailImage: "./assets/img/nike 5.png" , rating: "", description: "The Nike Air Max 95 moves with strength and fluidity inspired by the human body. The midsole represents the spine, graduated panels are the muscles, the lace loops are the shoe's ribs and the fabric in the upper is its skin."},
    {id: 6, name: "Jordan Zoom 92' PSG", gender: "Men's Shoe", colour: "Grey", price: "R 2 399.95", image: "./assets/img/Nike Jordan Zoom 92.jpg", detailImage: "./assets/img/nike 6.png" ,  rating: "", description: "A nod to '90s basketball shoes, the Zoom '92 focuses on comfort, while tapping into the bold, irreverent spirit of that era's designs. A stretchy sleeve and underfoot cushioning make for an effortless fit and feel. This version uses the colours and graphics of French football club Paris Saint-Germain."},
    {id: 7, name: "Nike RYZ 365", gender: "Women's Shoe", colour: "White", price: "R 1 599.95", image: "./assets/img/Nike RYZ 395.jpg", detailImage: "./assets/img/nike 7.png" , rating: "", description: "The Nike RYZ 365 brings you a futuristic take on the classic chunky sneaker of the mid-'90s. The large cut-outs in the soft foam midsole feature eye-catching geometric shapes and add a playful twist to the shoe's lifted stance."},
    {id: 8, name: "Nike Explore Strada", gender: "Men's Shoe", colour: "Black", price: "R 999.95", image: "./assets/img/Nike Explore Strada Black.jpg", detailImage: "./assets/img/nike 8.png" , rating: "", description: "Inspired by the unique style of the Nike React Element 55, the Nike Explore Strada features a woven upper, dual-tone colours and a memory-foam-infused sockliner for all-day modern style and comfort."},
    {id: 9, name: "NikeCourt Air Max", gender: "Men's Shoe", colour: "Green", price: "R 1 799.95", image: "./assets/img/Nike Court AirMax Wing Green.jpg", detailImage: "./assets/img/nike 9.png" , rating: "", description: "The NikeCourt Air Max Vapor Wing Premium is the perfect pairing of style and comfort. Soft leather elevates your look, while a visible Max Air unit cushions every step."},
    {id: 10, name: "Nike Air Max 270", gender: "Women's Shoe", colour: "Pink", price: "R 2 499.95", image: "./assets/img/Nike Air Max 270 Pink.jpg", detailImage: "./assets/img/nike 10.png" , rating: "", description: "Nike's first lifestyle Air Max, the Nike Air Max 270, brings you style, comfort and big attitude. The design draws inspiration from Air Max icons, showcasing Nike's greatest innovation with its large window and fresh array of colours."},
];

var feedBackArray = [
    {rating: "5", email: "", category: "Customer Service", content: "Connoisseur is absolutely amazing! Quick and easy to use."},
    {rating: "3", email: "", category: "Website", content: "The website is well designed!, little tweaks needed"},
    {rating: "2", email: "", category: "Other", content: "The delivery system is a bit slow, maybe improve communication"},
    {rating: "3", email: "", category: "Shoes", content: "Shoes are of high quality,they have a premium feel to them"},
    {rating: "4", email: "", category: "Customer Service", content: "Great engaging customer support, always happy to assist"},
];